[project]
name = "pyjam"
version = "0.1.0"
dependencies = ["arcade", "pyinstaller"]

[project.scripts]
pyjam = "pyjam.cli:run"

[tool.setuptools.packages.find]
where = ["src"]

[build.system]
requires = ["setuptools>=65.5"]
build-backend = "setuptools.build_meta"
